name: vuepress-deploy
on:
  push:
    branches:
      - master      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: 'ts/fermium'
      - name: Install dependencies
        run: yarn
      - name: Build VuePress
        run: yarn build
      - name: Deploy to Pages
        env:
         TZ: Asia/Shanghai
        run: |
         cd dist
         git config --global init.defaultBranch gh-pages
         git init
         git config user.name $GITHUB_ACTOR
         git config user.email ${{ secrets.GIT_EMAIL }}
         git add .
         git commit -m "deploy"
         git push -f https://$GITHUB_ACTOR:${{ github.token }}@github.com/$GITHUB_REPOSITORY.git gh-pages
